export { default as CustomersManagement } from './CustomersManagement';
export { default as GroupsProductManagement } from './GroupsProductManagement';
export { default as Landing } from './Landing';
export { default as OrdersManagement } from './OrdersManagement';
export { default as ProductsManagement } from './ProductsManagement';
export { default as SalesManagement } from './SalesManagement';
export { default as UsersManagement } from './UsersManagement';
export { default as HomeLayout } from './HomeLayout';
export { default as Error } from './Error';
